# Generated by Django 4.0 on 2022-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='general',
            field=models.TextField(null=True),
        ),
    ]
