# Generated by Django 4.0 on 2022-03-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_emp_id_delete_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_id',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='emp_id',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.employee'),
        ),
    ]
