# Generated by Django 4.0 on 2022-03-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_emp_id_emp_id_emp_id_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Emp_id',
        ),
    ]
