# Generated by Django 4.0 on 2022-03-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_employee_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
