# Generated by Django 4.0 on 2022-03-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_job_type_employee_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.job_type'),
        ),
    ]
