# Generated by Django 4.0 on 2022-03-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_remove_employee_job_type_employee_job_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_Type',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_type',
            field=models.ManyToManyField(to='my_app.job_type'),
        ),
    ]
