# Generated by Django 4.0 on 2022-03-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_rename_job_type_type_remove_employee_job_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Job_Type',
        ),
    ]
