# Generated by Django 4.0 on 2022-03-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_rename_type_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_type',
        ),
        migrations.DeleteModel(
            name='Job_Type',
        ),
    ]
